create table if not exists public.patients (
  id bigint generated by default as identity primary key,
  patient_id text not null unique,
  name text not null,
  age integer not null check (age > 0),
  gender text,
  blood_group text,
  contact text not null,
  address text,
  emergency_contact text,
  known_allergies text[] not null default '{}',
  chronic_conditions text[] not null default '{}',
  current_medications text[] not null default '{}',
  insurance_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_patients_patient_id on public.patients(patient_id);
